- cmd/dump.go
- cmd/validate.go
- internal/pkg/db/memdb.go
- internal/pkg/differ/differ.go
- internal/pkg/validator/validator.go
- pkg/api/apisix/apisix.go
- pkg/api/apisix/cluster.go
- pkg/api/apisix/plugin_metadata.go
- pkg/api/apisix/resource.go
- pkg/api/apisix/types/types.go
- pkg/api/apisix/types/types_test.go
- pkg/common/file.go
- pkg/data/events.go
- test/cli/cli_test.go
- test/cli/config/ci_config.go
- test/cli/scaffold/scaffold.go
- test/cli/suites-consumer-group/sdk.go
- test/cli/suites-consumer-group/sync.go
- test/cli/suites-consumer/sync.go
- test/cli/suites-global-rule/sync.go
- test/cli/suites-plugin-config/sync.go
- test/cli/suites-plugin-metadata/diff.go
- test/cli/suites-plugin-metadata/dump.go
- test/cli/suites-plugin-metadata/sdk.go
- test/cli/suites-plugin-metadata/testdata/test.yaml
- test/cli/suites-plugin-metadata/validate.go
- test/cli/suites/dump.go
- test/cli/suites/sync.go
- test/cli/testdata/test.yaml
Two problems here:
1. APISIX list plugin_metadata response doesn't contains metadata ID, have to patch it manually
2. APISIX validate API doesn't support plugin_metadata, function disabled for now
> feat: support plugin metadata

- cmd/configure.go
- cmd/diff.go
- cmd/dump.go
- cmd/ping.go
- cmd/root.go
- cmd/sync.go
- cmd/utils.go
- cmd/validate.go
- cmd/version.go
- test/cli/suites-consumer-group/validate.go
- test/cli/suites-consumer/validate.go
- test/cli/suites-global-rule/validate.go
- test/cli/suites-plugin-config/validate.go
- test/cli/suites/ping.go
- test/cli/suites/validate.go
Signed-off-by: Navendu Pottekkat <navendu@apache.org>
Improves the messages shown to the user to improve developer experience.
> fix: improve messages to users

- pkg/common/file.go
- test/cli/cli_test.go
- test/cli/config/ci_config.go
- test/cli/suites-usecase/sync-delete.go
- test/cli/suites-usecase/testdata/sync-delete-init.yaml
- test/cli/suites-usecase/testdata/sync-delete-updated.yaml
- test/cli/suites/dump.go
not a fix, but add test case for #20
closes #20
> test: add test case for sync-deletion usecase

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ISSUE_TEMPLATE/bug_report.yaml
- .github/workflows/ISSUE_TEMPLATE/feature_request.yaml
- .github/workflows/ISSUE_TEMPLATE/improve_docs.yaml
Adds basic issue and pull request templates.
> chore: add issue and PR templates

- README.md
- cmd/openapi2apisix.go
Adds documentation in the readme for the `openapi2apisix` subcommand.
Also improves messages similar to #36
> docs: openapi2apisix messages and usage

- cmd/dump.go
- internal/pkg/openapi2apisix/openapi2apisix.go
- test/scaffold/scaffold.go
> ci: fix lint

- cmd/dump.go
- cmd/validate.go
- internal/pkg/db/memdb.go
- internal/pkg/differ/differ.go
- internal/pkg/validator/validator.go
- pkg/api/apisix/apisix.go
- pkg/api/apisix/client.go
- pkg/api/apisix/cluster.go
- pkg/api/apisix/stream_route.go
- pkg/api/apisix/types/types.go
- pkg/api/apisix/upstream.go
- pkg/common/file.go
- pkg/data/events.go
- test/cli/cli_test.go
- test/cli/suites-stream-route/diff.go
- test/cli/suites-stream-route/dump.go
- test/cli/suites-stream-route/sdk.go
- test/cli/suites-stream-route/sync.go
- test/cli/suites-stream-route/testdata/test.yaml
- test/cli/suites-stream-route/validate.go
- test/scaffold/scaffold.go
Support stream_route and upstream.
> feat: stream route and upstream

- cmd/ping.go
- pkg/api/apisix/types/types.go
- test/cli/suites-basic/dump.go
- test/cli/suites-plugin-config/sync.go
- test/cli/suites-stream-route/dump.go
- test/cli/suites-stream-route/sdk.go
- test/cli/suites-stream-route/sync.go
- test/cli/suites-usecase/sync-delete.go
- test/mtls/suites-basic/dump.go
> feat: extend fields

- cmd/root.go
- pkg/api/apisix/types/types.go
> fix: err handing

- .github/workflows/cli_test.yaml
- test/cli/cli_test.go
- utils/quickstart.sh
Merge this once `apache/apisix:dev` get updated
> test: enable stream_route test

- cmd/openapi2apisix.go
- internal/pkg/openapi2apisix/openapi2apisix.go
- internal/pkg/openapi2apisix/openapi2apisix_test.go
- pkg/api/apisix/types/resource_schema_test.go
- pkg/api/apisix/types/types.go
- pkg/common/utils.go
Support more fields in openapi convertion.
> feat: support openapi to upstream

- apps/cli/src/command/index.ts
> feat: bump to 0.12.0

- README.md
Update the installation instructions in readme to use the script and the latest version.
> doc: update installation instructions in readme

- .github/workflows/e2e.yaml
Test API7 Backend on API7 3.2.14.1
> ci(api7): e2e test on 3.2.14.1

- .github/workflows/e2e.yaml
- apps/cli/src/command/index.ts
> feat: bump to 0.12.1

- .github/workflows/e2e.yaml
> ci: test api7 on 3.2.14.3

- apps/cli/src/command/index.ts
Modify the version to `0.12.2`.
> feat: bump to 0.12.2

- apps/cli/src/command/index.ts
Bump version to 0.13.0
In this version, we will drop support for API7 3.2.13.0.
> feat: bump to 0.13.0

- libs/converter-openapi/src/index.ts
- libs/converter-openapi/src/schema.ts
- libs/converter-openapi/tsconfig.lib.json
- Optimize the error output of the validator in the OpenAPI converter.
| Previous | Current |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/3ec88e75-279c-4aa8-a929-638853242e90) | ![image](https://github.com/user-attachments/assets/2831fbd2-b2d1-4947-afb5-e96cb3fc1123) | 
- Add debugging verbose for raw errors in the validator.
> feat: improve oas converter error output

- apps/cli/src/command/index.ts
> feat: bump to 0.14.0

- libs/backend-api7/e2e/resources/route.e2e-spec.ts
- libs/backend-api7/src/transformer.ts
- libs/backend-api7/src/typing.ts
Add specific timeout configuration on route-level for API7.
> feat(api7): support route-level timeout

- libs/backend-api7/e2e/resources/consumer.e2e-spec.ts
- libs/backend-api7/e2e/support/utils.ts
E2E testing for modifying consumer credentials.
> test(api7): fix consumer credentials

- apps/cli/src/command/index.ts
> feat: bump to 0.15.0

- apps/cli/src/linter/schema.ts
- apps/cli/src/linter/specs/common.spec.ts
- schema.json
Update lint schema for custom id.
> feat(core): update custom id schema

- apps/cli/src/command/index.ts
> feat: bump to 0.16.0

- apps/cli/src/command/index.ts
> feat: bump to 0.16.1

- apps/cli/src/command/index.ts
> feat: bump to 0.16.2

- .github/workflows/docker.yaml
Container tag pattern error makes the build fail, fix it.
> fix: docker release tag typo

- libs/backend-apisix/e2e/sync-and-dump-1.e2e-spec.ts
- libs/backend-apisix/src/transformer.ts
> fix(apisix): service missing hosts

- apps/cli/src/command/index.ts
> feat: bump to 0.17.0

- apps/cli/src/command/diff.command.ts
- apps/cli/src/command/sync.command.ts
The example in sync incorrectly mentions `adc diff`, fix it.
> fix(core): sync command example typo

- apps/cli/project.json
- apps/cli/src/command/index.ts
- apps/cli/src/command/ingress-sync.command.ts
- apps/cli/src/main.ingress.ts
- libs/backend-api7/src/operator.ts
Add a special entry used by Ingress Controller, which requires special build options and therefore will not be included in the general release. As its embedded use indicates, it doesn't need to be included in the general release either.
Some of its special things:
- All other commands except `sync` and the built-in `help` have been removed.
- The `sync` command uses stdout and stderr to report results and unrecoverable errors (usually program crashes).
- It does not interrupt the execution flow when some operations fail. Even if a partial resource synchronization fails, it just reports it without interrupting operations that have not yet been executed. (except for unrecoverable errors)
> feat(core): add ingress entrypoint

- apps/cli/project.json
- apps/cli/src/command/ingress-sync.command.ts
- apps/cli/src/main.ingress.ts
- apps/cli/src/main.ts
Embedding ADC ingress mode into the binary and let it be controlled by environment variables.
> feat(core): all in one ingress mode

- apps/cli/src/command/utils.ts
- apps/cli/src/main.ts
- libs/backend-api7/e2e/support/utils.ts
- libs/backend-api7/src/fetcher.ts
- libs/backend-api7/src/index.ts
- libs/backend-api7/src/operator.ts
- libs/backend-apisix/e2e/support/utils.ts
- libs/backend-apisix/e2e/sync-and-dump-1.e2e-spec.ts
- libs/backend-apisix/src/fetcher.ts
- libs/backend-apisix/src/index.ts
- libs/backend-apisix/src/operator.ts
- libs/backend-apisix/src/typing.ts
- libs/backend-apisix/src/utils.ts
- libs/sdk/src/backend/index.ts
- libs/sdk/src/backend/utils.ts
- package.json
- pnpm-lock.yaml
Rewrite APISIX as an rxjs-driven backend implementation.
> feat(apisix): rewrite apisix backend

- .github/workflows/release.yaml
- apps/cli/src/command/index.ts
- libs/tools/src/docker/Dockerfile
- package.json
- pnpm-lock.yaml
> feat: bump to 0.18.0

- apps/cli/src/command/utils.ts
- apps/cli/src/differ/differv3.ts
- apps/cli/src/differ/specs/service-upstream.spec.ts
- apps/cli/src/linter/schema.ts
- apps/cli/src/linter/specs/upstream.spec.ts
- apps/cli/src/tasks/lint.ts
- libs/backend-api7/e2e/resources/service-upstream.e2e-spec.ts
- libs/backend-api7/src/fetcher.ts
- libs/backend-api7/src/index.ts
- libs/backend-api7/src/operator.ts
- libs/backend-api7/src/transformer.ts
- libs/backend-api7/src/typing.ts
- libs/sdk/src/core/index.ts
- schema.json
API7 introduced multi-upstream features of the service for canary releasing since 3.5, this PR will support it.
> feat(api7): support multiple upstream of service

- libs/backend-apisix/src/fetcher.ts
If APISIX does not have stream proxy enabled, its Admin API will return `400 Bad Request` on the stream route API, and the ADC should tolerate this error since it is common to not enable stream proxy.
Fixes #251
> fix(apisix): tolerate instance without stream proxy enabled

- apps/cli/src/command/index.ts
> feat: bump to 0.19.0

- README.md
Remove the hardcoded `0.12.0` download link from README
> docs(readme): remove hardcoded download link

- libs/backend-apisix-standalone/src/operator.ts
- libs/backend-apisix-standalone/src/transformer.ts
The `immerjs` consumes most of the CPU time in the apisix-standalone backend, and to further improve its sync performance, these `produce()` have been modified to be pure JS objects.
> perf(apisix-standalone): remove immerjs

- apps/cli/src/linter/exporter.ts
- apps/cli/src/linter/schema.ts
- apps/cli/src/linter/specs/common.spec.ts
- apps/cli/src/linter/specs/consumer.spec.ts
- apps/cli/src/linter/specs/route.spec.ts
- apps/cli/src/linter/specs/schema-json.spec.ts
- apps/cli/src/linter/specs/ssl.spec.ts
- apps/cli/src/linter/specs/upstream.spec.ts
- apps/cli/src/tasks/lint.ts
- libs/backend-apisix-standalone/src/typing.ts
- libs/converter-openapi/src/index.ts
- package.json
- pnpm-lock.yaml
- schema.json
Move linter to zod4, and use the new native zod to jsonschema generator.
**There are changes to the content and format of human-readable bug reports. This is not structured output, and there is no backward compatibility guarantee.**
> feat(core): move linter to zod4

- .github/workflows/docker.yaml
Build the dev image for PRs committed to the main branch.
> feat(ci): build dev image for commit on main branch
