README.md

Signed-off-by: Navendu Pottekkat <navendu@apache.org>
Adds documentation on using different subcommands to the readme.

doc: add documentation to readme

---

.github/workflows/cli_test.yaml

Signed-off-by: Navendu Pottekkat <navendu@apache.org>
Pins the Ginkgo version used in CI to the Ginkgo version used in the code to ensure parity in tests.
Before:
After:

fix: pin Ginkgo version in CI

---

CONTRIBUTING.md

Fixes #30 
Adds a contributor guide with info on how to build and run the code.

docs: create a contributor guide

---

cmd/configure.go
cmd/root.go

Running `adc configure` for the first time would first initialize a configuration file instead of throwing an error.
Current UX:
```shell
adc configure
Config file not found at $HOME/.adc.yaml. Creating...
Please enter the APISIX server address: 
```
Previous UX:
```shell
adc configure
Fatal to read config file, please run `adc configure` to configure the client first.
Please input the server address:
```
Fixes #39

fix: `adc configure` initializes configuration file

---

.github/workflows/docker.yml

Added workflow to build & publish image

---

cmd/sync.go
pkg/data/events.go
pkg/data/events_test.go
test/cli/suites-basic/diff.go
test/cli/suites-consumer-group/diff.go
test/cli/suites-consumer/diff.go
test/cli/suites-global-rule/diff.go
test/cli/suites-plugin-config/diff.go
test/cli/suites-plugin-metadata/diff.go
test/mtls/suites-basic/diff.go

chore: update output for diff

---

cmd/root.go
go.mod
go.sum

fix: config flag

---

README.md

[Added the missing `.`.](docs: fix incorrect apisix.yaml)

docs: fix incorrect apisix.yaml

---

cmd/configure.go
cmd/ping.go
cmd/root.go
pkg/api/apisix/apisix.go
pkg/api/apisix/cluster.go
test/cli/suites-basic/ping.go
test/mtls/suites-basic/ping.go

Some versions don't have validate api.

feat: use admin-api to ping

---

cmd/configure.go
cmd/root.go

Handling a different scenario just for the config command is different. This approach makes it better by showing warnings indicating the lack of a configuration file. Now commands that require a configuration file ask users to run `adc configure`, and if the configuration file is not present, it is shown as a warning.
In the `adc configure` subcommand, when it is run initially without the configuration file being present, will show that the configuration file is not present and then proceed to create one without needing the `-f` flag to overwrite the created file.
```text
➜  adc sync
Configuration file /Users/navendu/.adc.yaml doesn't exist.
ADC isn't configured, run `adc configure` to configure ADC.
➜  adc configure
Configuration file /Users/navendu/.adc.yaml doesn't exist.
Please enter …
```

fix: initial run of `adc configure` does not throw error

---

README.md
install.sh

Adds an install script that users can just run, and it will install the appropriate version of the ADC binary for macOS and Linux.
TODO:
We need to serve this file similar to how we serve https://run.api7.ai/apisix/quickstart
I suggest this URL https://run.api7.ai/adc/install
Once we do that, users can install ADC by just running `curl -sL https://run.api7.ai/adc/install | sh`.
@juzhiyuan Can you help with this?

feat: add an install script for easy install

---

.github/workflows/e2e.yaml
.github/workflows/unit.yaml
apps/cli/src/command/dump.command.ts
libs/backend-api7/src/fetcher.ts
libs/backend-api7/src/index.ts
libs/backend-api7/test/fetcher.spec.ts
libs/backend-api7/tsconfig.spec.json
libs/sdk/src/backend/index.ts

Implement API-level resource filtering on API7 backend, i.e., when a user specifies `include-resource-type` or `exclude-resource-type`, it will no longer fetch a specific resource type from the API7 Enterprise API.

feat: api7 API-level resource type filter

---

libs/backend-api7/e2e/label-selector.e2e-spec.ts
libs/backend-api7/src/fetcher.ts
libs/backend-api7/src/utils.ts
libs/backend-apisix/src/utils.ts

The current API7 backend uses an implementation that pulls completely and performs label filtering locally. This can be inefficient when the number of potential resources is high.
This PR moves label filtering to the API7 API level, where the server performs resource filtering and only returns resources that match the labeling rules.
It supports the following resource types:
- Consumer
- SSL
Resource types that will not be supported (These resources do not have a labels field):
- Global Rule
- Plugin Metadata
Resources that may be supported later:
- Service: Right now, its not supported for labels based filtering, we will add support for it when the server starts supporting it.
Even though services do not perform API-level label filtering, label filtering will still work and its mode of …

feat(api7): support API-level label selector

---

apps/cli/src/command/diff.command.ts
apps/cli/src/command/utils.spec.ts
apps/cli/src/command/utils.ts

There have long been calls from users for ADC to add support for environment variable references in declarative API files, which would help avoid hard-coding secret values.
Yes, it has become a reality.
With this PR, users will be able to reference an environment variable in a YAML declarative API file using syntax like `${ENV_VAR}`.
It will work no matter which backend you use. The only restriction is that only values are allowed to use environment variables, while property names in objects are not.

feat(core): support resolve env var syntax in input

---

apps/cli/src/command/lint.command.ts
apps/cli/src/linter/exporter.ts
apps/cli/src/linter/schema.ts
libs/sdk/src/core/index.ts
schema.json

The current linter schema is somewhat outdated and incomplete, this PR fixes these flaws and provides a JSON Schema export for the benefit of IDE users.
As far as I know, you can enable schema checking in your VSCode using a syntax like:
```
services: []
```
Note that the file schema.json is generated by the program, so the JSON Schema may not fully reflect the complete configuration schema, as some of the checksums are done at runtime by code.
I don't think you need to worry about this, execute adc lint to check the declaration file in its entirety.
In addition to this, I must say that since API7 and APISIX do not currently support the same features, and it is possible that a feature is not yet implemented on a particular platform, the configuration checked by lint does not always ensure …

feat: improve linter

---

apps/cli/src/command/diff.command.ts
apps/cli/src/command/helper.ts
apps/cli/src/command/sync.command.ts
apps/cli/src/linter/schema.ts

The current lint in the ADC is manual and will not be executed by default when diff and sync are executed, which can lead to unintended commit behavior, so this PR lists lint as a step in the diff and sync commands.
If you wish to turn off lint checking on diff and sync, you can use `--no-lint` to disable lint checking.

feat(core): add lint on diff and sync in default

---

apps/cli/src/linter/schema.ts
libs/backend-apisix/e2e/assets/apisix_conf/http.yaml
libs/backend-apisix/e2e/sync-and-dump-1.e2e-spec.ts
libs/backend-apisix/src/transformer.ts
libs/backend-apisix/src/typing.ts
schema.json

Synchronization fails due to the fact that APISIX resources are non-standard, e.g. the stream route does not have a name field that can be used to store names.
This PR has some compatibility fixes, it uses `labels` to store a key called `__ADC_NAME` to store the name, which is transparent to the user, and is automatically added during sync and removed during dump.
I'm going to push for standardization of resource objects in APISIX, but until that's done, this compatibility measure is unavoidable.

fix(apisix): store stream route name correctly

---

.github/workflows/release.yaml
apps/cli/src/command/index.ts

Bump version to `0.12.0-alpha.1`

feat: bump to 0.12.0-alpha.1

---

.github/workflows/update-s3-and-cloudfront.yaml
s3/install

Adds an install script and a workflow to publish the script to our s3 bucket. The install script downloads and installs the appropriate ADC binary to make it easy for users to use ADC.
A user should be able to install ADC by just running:
```shell
curl -sL https://run.api7.ai/adc/install | sh
```
Updates to the documentation, both in readme and the docs website will be made after this PR is merged and tested.
Test:

ci: add install script

---

apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/upstream.spec.ts

The current upstream schema lists `nodes` as a required field, thus preventing the use of service discovery.
Now `nodes` will be optional, and an additional checker will ensure that one of `nodes` and `discovery` is set.

fix(core): upstream linter check either nodes or service discovery

---

apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/ssl.spec.ts
schema.json

Support for data plane SSL secret/env ref.

fix: ssl secret ref

---

apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/route.spec.ts
schema.json

fix(core): route vars expr schema

---

apps/cli/src/command/convert.command.ts
apps/cli/src/command/diff.command.ts
apps/cli/src/command/dump.command.ts
apps/cli/src/command/helper.ts
apps/cli/src/command/index.ts
apps/cli/src/command/lint.command.ts
apps/cli/src/command/ping.command.ts
apps/cli/src/command/sync.command.ts
libs/backend-api7/src/index.ts

Makes improvements to the inline documentation of subcommands so that they are consistent.
I will also be improving the examples shown to cover typical use cases and making some other UX improvements. I realized it might take some time and become a bigger PR so this is a small PR to make some initial changes.

fix: improve inline documentation

---

apps/cli/src/command/convert.command.ts
apps/cli/src/command/diff.command.ts
apps/cli/src/command/dump.command.ts
apps/cli/src/command/helper.ts
apps/cli/src/command/lint.command.ts
apps/cli/src/command/ping.command.ts
apps/cli/src/command/sync.command.ts

Adds inline examples to subcommands to improve ease of use.
Now, users can easily refer to the examples to figure out specific flows instead of having to navigate through each option.
The examples are added in an "easy to copy" way with the description of each example in a shell comment form similar to other popular CLIs like `kubectl`. Examples are also added before the `Options` section to make it obvious. Users can look at the docs for specific options after they find the example they want.

feat: add inline examples

---

.github/workflows/e2e.yaml
apps/cli/src/differ/differv3.ts
apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/common.spec.ts
libs/backend-api7/e2e/misc.e2e-spec.ts
libs/backend-api7/src/index.ts
libs/backend-apisix/src/fetcher.ts
libs/sdk/src/core/resource.ts
schema.json

Loosen the name max length checking rules in schema.

feat(core): looser name length

---

.github/workflows/e2e.yaml
apps/cli/src/command/convert.command.ts
apps/cli/src/command/diff.command.ts
apps/cli/src/command/dump.command.ts
apps/cli/src/command/helper.ts
apps/cli/src/command/index.ts
apps/cli/src/command/lint.command.ts
apps/cli/src/command/ping.command.ts
apps/cli/src/command/sync.command.ts
apps/cli/src/differ/differv3.ts
apps/cli/src/linter/exporter.ts
apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/common.spec.ts
libs/backend-api7/e2e/misc.e2e-spec.ts
libs/backend-api7/e2e/sync-and-dump-1.e2e-spec.ts
libs/backend-api7/src/index.ts
libs/backend-api7/src/transformer.ts
libs/backend-api7/src/typing.ts
libs/backend-apisix/src/fetcher.ts
libs/sdk/src/core/resource.ts
schema.json

In recent releases, API7 has added support for priority on routes, and this PR adds the priority field.

feat(api7): add priority support

---

apps/cli/src/command/dump.command.ts
apps/cli/src/command/ping.command.ts
apps/cli/src/command/sync.command.ts

Prints an error when a JS error is happening.

feat: output more logs when errors happened

---

.github/workflows/e2e.yaml
libs/backend-api7/e2e/sync-and-dump-1.e2e-spec.ts
libs/backend-api7/src/transformer.ts
libs/backend-api7/src/typing.ts

According to the previous API7 version, multiple uris in routes were not exposed by the dashboard, so ADC also did not provide this feature, this status quo has been enhanced and ADC will also support this feature.

feat(api7): allow mutliple uris in route

---

.github/workflows/e2e.yaml
apps/cli/src/command/utils.ts
libs/backend-apisix/e2e/assets/docker-compose.yaml
libs/backend-apisix/e2e/resources/consumer.e2e-spec.ts
libs/backend-apisix/e2e/support/utils.ts
libs/backend-apisix/e2e/sync-and-dump-1.e2e-spec.ts
libs/backend-apisix/src/fetcher.ts
libs/backend-apisix/src/index.ts
libs/backend-apisix/src/operator.ts
libs/backend-apisix/src/transformer.ts
libs/backend-apisix/src/typing.ts
libs/backend-apisix/src/utils.ts

Add consumer credentials support to APISIX as well.

feat(apisix): support consumer credentials

---

apps/cli/src/linter/exporter.ts
apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/upstream.spec.ts
libs/backend-api7/README.md
libs/backend-api7/src/typing.ts
libs/sdk/src/core/index.ts
schema.json

API7 let the upstream mtls settings as `cert` and `key` instead of `client_cert` and `client_key` in the converter, which is not schema compliant, so fix it.
Also, cert and key do not emphasize their roles, so they need to be modified.

fix(api7): mismatched fields in upstream mtls

---

apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/common.spec.ts
schema.json

More loose custom resource ID lengths.

feat(core): loose custom resource id length

---

apps/cli/src/command/diff.command.ts
apps/cli/src/command/sync.command.ts
package.json
pnpm-lock.yaml

Support for file path inputs using glob expressions, ADC will automatically expand them and find each expected file.
Note that you must ensure that glob expressions are not parsed by the shell you are using, which requires you to wrap path strings with `"`.

feat(core): support glob file path

---

apps/cli/src/command/dump.command.ts

feat(core): dump sorted yaml

---

.github/workflows/e2e.yaml
libs/backend-api7/e2e/resources/route.e2e-spec.ts
libs/backend-api7/src/index.ts
libs/backend-api7/src/operator.ts
libs/backend-api7/src/transformer.ts
libs/backend-api7/src/typing.ts
libs/sdk/src/core/index.ts

Sync and dump vars expressions in route for API7.
Minimum supported version 3.2.16.4

feat(api7): support route vars expr

---

libs/backend-apisix/e2e/resources/consumer.e2e-spec.ts
libs/backend-apisix/e2e/resources/upstream.e2e-spec.ts
libs/backend-apisix/src/transformer.ts

When using service discovery, nodes may be null, so it handler needs to be somewhat fault tolerant.

fix(apisix): upstream nodes should be allowed to be null

---

apps/cli/src/command/diff.command.ts
apps/cli/src/command/index.ts
apps/cli/src/command/sync.command.ts

Specify a remote state file, which will allow the ADC to skip the initial dump process and use the ADC configuration contained in the state file directly.
**This is an experimental feature for some specific purposes and you should not use and rely on them as this may be removed at any time in the future.**

feat(core): add remote state file as experimental feature

---

apps/cli/src/command/convert.command.ts

Add the ability to convert multiple OAS specs simultaneously to a single ADC configuration to the OAS converter.

feat(core): support multiple file input for OAS converter

---

apps/cli/src/command/index.ts
libs/backend-api7/src/index.ts
libs/sdk/src/utils.ts

This patch will allow requests on the API7 backend to be as parallel as possible, and it will improve ADC execution time to some extent.
**This is an experimental feature for some specific purposes and you should not use and rely on them as this may be removed at any time in the future.**

feat(api7): add parallel backend request as experimental feature

---

libs/backend-api7/src/index.ts
libs/backend-apisix/src/index.ts

Enabled connection pool on the API7 and APISIX backend APIs to enhance their performance and time consumption when sending large numbers of API requests.
Specifically, instead of establishing a new TCP connection on each request, ADC will attempt to reuse existing connections.

feat(backend): enable keepalive for backend api call

---

libs/backend-api7/src/index.ts

Fix: unexpectedly passing the empty string as the gateway group id.

fix(api7): unexpectedly pass the empty string gateway group id

---

apps/cli/src/command/ingress-sync.command.ts

The remote configuration was incorrectly cleared in ingress mode, which invalidated the delete operation. Fix it.

fix(core): incorrect empty remote in ingress mode

---

apps/cli/src/command/ingress-sync.command.ts
apps/cli/src/command/sync.command.ts
libs/backend-api7/e2e/misc.e2e-spec.ts
libs/backend-api7/e2e/support/global-setup.ts
libs/backend-api7/e2e/support/utils.ts
libs/backend-api7/src/fetcher.ts
libs/backend-api7/src/index.ts
libs/backend-api7/src/operator.ts
libs/backend-apisix/e2e/support/utils.ts
libs/backend-apisix/e2e/sync-and-dump-1.e2e-spec.ts
libs/backend-apisix/src/fetcher.ts
libs/backend-apisix/src/index.ts
libs/backend-apisix/src/operator.ts
libs/sdk/src/backend/index.ts

Improved error handling in API7 and APISIX backends, which can now run in continue-on-failure and exit-on-failure modes.
In the ADC CLI mod, it will continue to run in fail-on-exit mode as in previous versions, while Ingress mode allows errors to be logged and returned instead of interrupting synchronization.

feat: imporve backend error handling

---

apps/cli/src/linter/schema.ts
apps/cli/src/linter/specs/common.spec.ts

The lint currently performs strict checks on configurations but will encounter problems when the user tries to use environment variables, e.g., on `port` fields (integers), lint will fail since the environment variable will always be parsed as a string.
This PR introduces automatic conversion for them, when a string is entered on those fields that require numeric input, ADC will now automatically parse the string to a number and lint will not report an error.
Fix: #243

fix(core): lint does not allow string input on numeric fields

---

apps/cli/src/command/utils.ts
apps/cli/src/utils/listr.ts
libs/backend-api7/src/index.ts
libs/backend-apisix/src/index.ts
libs/converter-openapi/src/index.ts
libs/sdk/src/backend/index.ts

According to the report in #251, log scope on the APISIX backend are incorrectly displayed as API7, I fix it in this PR.
Fixes #251

fix(apisix): log scope typo

---

apps/cli/src/differ/differv3.ts
apps/cli/src/differ/specs/basic.spec.ts
apps/cli/src/differ/specs/usecase.spec.ts
libs/backend-apisix/e2e/resources/service-upstream.e2e-spec.ts
libs/backend-apisix/src/fetcher.ts
libs/backend-apisix/src/operator.ts
libs/backend-apisix/src/transformer.ts
libs/backend-apisix/src/typing.ts

As a successor to #252, similar functionality is supported on APISIX.
Since APISIX does not natively support multiple upstreams associated with the service, this is simulated by core upstream resource objects and a specific label field. They have the same effect.

feat(apisix): support multiple upstream of service

---

apps/cli/src/command/dump.command.ts
apps/cli/src/command/utils.ts

1. Ensure that the username in the consumer is always displayed before the plugins
2. Ensure that each resource is sorted using its unique readable name, e.g., name, username, etc.
Improved comparability when exporting multiple times.
Fix #259

feat(core): sort the configuration by readable name during dump

---

.github/workflows/e2e.yaml
apps/cli/src/command/utils.spec.ts
apps/cli/src/command/utils.ts

Previously, `${X}` in a YAML value would be unconditionally parsed as an environment variable, or replaced with an empty string if the environment variable did not exist.
It is difficult to represent APISIX variables (like `${http_x_api_key}`) in YAML if they are required in some plugin configurations.
So this PR introduces an escape `\\` so that when you use `\\${X}`, the `${X}` will be left as is and not replaced, and the escape character will be discarded.

feat(core): allow keep var syntax in yaml via escaping chars

---

apps/cli/src/tasks/load_remote.ts

When the label selector is used during synchronization, the ADC performs filtering on the dump results to exclude those resources that should be ignored before discrepancy checking, which requires modification of the dump results.
However, some ADC backend implementations return an immutable object to avoid accidental modifications at runtime, which is implemented via Object.frozen, which results in an error when ADC tries to modify the data.
This PR will fix it by using a deep copy to unfreeze the object, which acts as a quick fix. After that, it will be refactored to be completely immutable.
Fixes #263

fix: modify frozen immutable objects

---

apps/cli/webpack.config.js
libs/backend-api7/src/operator.ts
libs/backend-apisix/src/operator.ts
package.json
pnpm-lock.yaml

Errors may occur when the backend calls the API, which then reports the error and exits, some of the code used to generate the error message contains errors that are not displayed correctly, and the error stack is not clear because the project does not include a source map release.
This PR improves the error reporting code and provides source map export, now it works out of the box.
Fixes #261

fix(backend): failed to report operation error

---

apps/cli/src/command/index.ts
libs/backend-apisix/README.md
package.json

Bump version to 0.19.1.
It contains some fixes on the APISIX backend.
It also corrects a documented error in `package.json`, namely the license section, which has always been the Apache-2.0 open source used by ADC based on the LICENSE file in its root directory, not the MIT in package.json.
We don't publish the package separately to npm, so this doesn't involve changing the license, which used to be Apache-2.0 and still is.

feat: bump to 0.19.1

---

libs/backend-apisix-standalone/src/transformer.ts

Move the zod-based transformer to a regular function.
Zod cannot perform fault-tolerant conversions, meaning that if the input source data does not match the schema, the conversion will fail. This is unacceptable, so we cannot continue to use zod as a transformer.

fix(apisix-standalone): remove zod-based transformer

---

apps/cli/src/differ/differv3.ts
apps/cli/src/differ/specs/consumer.spec.ts
libs/backend-apisix-standalone/e2e/resources/consumer.e2e-spec.ts
libs/backend-apisix-standalone/src/operator.ts
libs/backend-apisix-standalone/src/transformer.ts
libs/backend-apisix-standalone/src/typing.ts

1. The consumer can't be removed correctly
The consumer uses `username` as the ID instead of `id`, and the current code doesn't handle this fact correctly, so the consumer can't be deleted correctly.
2. Consumer credentials cannot be removed correctly & consumer's `conf_version` unexpected updates
Consumers use a specific ID format, `{consumer_username}/credentials/{cred_id}`, which is not handled correctly by the current code, so the modification and deletion will be unsuccessful.
On top of that, because the remote IDs of these credentials are not handled correctly, the IDs will always be treated as changed (so the ADC will emit a delete and a create event), which makes the conf_version always change.
The current implementation of differ does not raise the consumer_credential delete …

fix(apisix-standalone): consumer sync exception

---

apps/cli/src/command/ping.command.ts
apps/cli/src/command/utils.ts

Remove `Apache APISIX backend is experimental!` log.

chore(apisix): remove experimental log

---

apps/cli/e2e/server/basic.e2e-spec.ts
apps/cli/src/command/helper.ts
apps/cli/src/command/ingress-server.command.ts
apps/cli/src/server/index.ts

Support for configuring the ingress server to listen on hostnames and ports via `--listen`.
(e.g., `--listen http://1.1.1.1:5432`)
It does not support TLS at this time.
Fix a bug introduced by #305.

feat(core): configurable ingress server listen

---

apps/cli/src/command/ingress-server.command.ts

The ingress server mode will now try to read the TLS certificate when it starts and report an error if it is not provided.

fix(core): ingress server listen no TLS endpoint

---

apps/cli/e2e/server/basic.e2e-spec.ts
apps/cli/src/command/ingress-server.command.ts
apps/cli/src/server/index.ts

Add the health/ready endpoint for Kubernetes probes.
```
--listen-status 3001
```
```
curl http://127.0.0.1:3001/healthz/ready -i
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 2
Connection: keep-alive
Keep-Alive: timeout=5
OK
```

feat(core): ingress server status endpoint

---

libs/converter-openapi/README.md

docs(converter-openapi): fix typo

---

libs/backend-apisix-standalone/e2e/cache.e2e-spec.ts
libs/backend-apisix-standalone/e2e/resources/service.e2e-spec.ts
libs/backend-apisix-standalone/src/operator.ts
libs/backend-apisix-standalone/src/transformer.ts

Currently, ADC uses timestamps with second precision as the conf version, which may not be sufficient if the ingress controller sends requests quickly.
This PR changes the timestamp to millisecond precision, which is expected to be sufficient. Its value range will be within the numeric range of JavaScript and LuaJIT, `2^53-1`, which is not a concern.

feat(apisix-standalone): use millisecond timestamp as conf version

---

libs/backend-apisix-standalone/e2e/resources/service-inline-upstream.e2e-spec.ts
libs/backend-apisix-standalone/src/operator.ts

I implemented inline upstream splitting in #319, but there seem to be some issues with the update and delete logic, specifically:
1. The split upstream may not be updated correctly.
2. When only the inline upstream is updated in the service, the service conf version is incorrectly increased.
This PR thoroughly reorganized this section and optimized the code.

fix(apisix-standalone): handle inline upstream update and delete

---

libs/backend-apisix-standalone/e2e/resources/service-inline-upstream.e2e-spec.ts
libs/backend-apisix-standalone/src/operator.ts

Add a test case that performs multiple inline upstream updates.

test(apisix-standalone): add inline upstream update 2 times case

---

libs/backend-apisix-standalone/src/operator.ts

Currently, if there are no change events, ADC will not actually issue PUT requests.
This causes problems when adding or removing APISIX instances, as those synchronous requests will not actually occur, preventing the data plane from being configured.

fix(apisix-standalone): ensure PUT sent when no diff events

---

libs/backend-apisix-standalone/README.md
libs/backend-apisix-standalone/src/operator.ts
libs/backend-apisix-standalone/src/transformer.ts
libs/backend-apisix-standalone/src/typing.ts
libs/sdk/src/core/index.ts

Add support for upstream health checks and service discovery in the apisix-standalone backend.
ref: https://github.com/apache/apisix-ingress-controller/issues/2542

feat(apisix-standalone): support upstream healthcheck and service discovery

---

.github/workflows/e2e.yaml
libs/backend-api7/e2e/resources/service-upstream.e2e-spec.ts
libs/backend-api7/package.json
libs/backend-api7/src/operator.ts
package.json
pnpm-lock.yaml

Due to inherent differences between API7 and APISIX, such as the association between upstreams and services, and between credentials and consumers, we encounter issues if resource updates and deletions are still handled according to APISIX's rules.
For instance, APISIX requires deleting a service referencing an upstream ID before removing that upstream. In API7, deleting a service automatically removes all associated upstreams. This would cause 404 errors.
This PR introduces a workaround: if an upstream is deleted due to service removal, it no longer triggers sequential deletion. Instead, the server automatically performs cascading deletion. Consumers and credentials follow this same logic.

fix(backend-api7): duplicate removal of upstream and credentials

---

libs/backend-apisix-standalone/src/transformer.ts

When using upstream service discovery in apisix standalone, nodes will conflict with them.
This PR fixes the issue by performing the conversion during the dump only when nodes exist.

fix(apisix-standalone): conflict between upstream nodes and service discovery
